In [3]:
# Mounted google drive for
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
#Import the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Imported dataset
file_path = '/content/drive/MyDrive/AI_Healthcare_Diagnosis_system/raw_data.xlsx'
df = pd.read_excel(file_path)

# Showing   First 5 rows
df.head()

,Disease,Count of Disease Occurrence,Symptom
0,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0008031_pain chest
1,NaN,NaN,UMLS:C0392680_shortness of breath
2,NaN,NaN,UMLS:C0012833_dizziness
3,NaN,NaN,UMLS:C0004093_asthenia
4,NaN,NaN,UMLS:C0085639_fall

In [6]:
df.shape                        #Checking for rows and columns

(1866, 3)

In [8]:
df.isnull().sum()              # CHecking for the null values

Disease                        1732
Count of Disease Occurrence    1732
Symptom                           1
dtype: int64

In [10]:
df.columns                      # CHecking for the columns available

Index(['Disease', 'Count of Disease Occurrence', 'Symptom'], dtype='object')

In [12]:
df.info()                       # Provide the information abount the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1866 entries, 0 to 1865
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Disease                      134 non-null    object
 1   Count of Disease Occurrence  134 non-null    float64
 2   Symptom                      1865 non-null   object
dtypes: float64(1), object(2)
memory usage: 43.9+ KB

In [14]:
# Number of Unique Diseases
df['Disease'].nunique()

134

In [15]:
# Number of Unique Symptoms
df['Symptom'].nunique()

401

In [16]:
df.head(15)

,Disease,Count of Disease Occurrence,Symptom
0,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0008031_pain chest
1,NaN,NaN,UMLS:C0392680_shortness of breath
2,NaN,NaN,UMLS:C0012833_dizziness
3,NaN,NaN,UMLS:C0004093_asthenia
4,NaN,NaN,UMLS:C0085639_fall
5,NaN,NaN,UMLS:C0039070_syncope
6,NaN,NaN,UMLS:C0042571_vertigo
7,NaN,NaN,UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...
8,NaN,NaN,UMLS:C0030252_palpitation
9,NaN,NaN,UMLS:C0027497_nausea
10,NaN,NaN,UMLS:C0002962_angina pectoris
11,NaN,NaN,UMLS:C0438716_pressure chest
12,UMLS:C0011847_diabetes,1421.0,UMLS:C0032617_polyuria
13,NaN,NaN,UMLS:C0085602_polydypsia
14,NaN,NaN,UMLS:C0392680_shortness of breath

In [18]:
# We are using ffill for filling the nan values because there is multiple rows representing symptoms for same disease

df['Disease'] = df['Disease'].ffill()

In [19]:
# We are using ffill for filling the nan values in because there is multiple rows representing symptoms for same Count of Disease Occurrence

df['Count of Disease Occurrence'] = df['Count of Disease Occurrence'].ffill()

In [20]:
df.head(15)

,Disease,Count of Disease Occurrence,Symptom
0,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0008031_pain chest
1,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0392680_shortness of breath
2,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0012833_dizziness
3,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0004093_asthenia
4,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0085639_fall
5,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0039070_syncope
6,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0042571_vertigo
7,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...
8,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0030252_palpitation
9,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0027497_nausea
10,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0002962_angina pectoris
11,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0438716_pressure chest
12,UMLS:C0011847_diabetes,1421.0,UMLS:C0032617_polyuria
13,UMLS:C0011847_diabetes,1421.0,UMLS:C0085602_polydypsia
14,UMLS:C0011847_diabetes,1421.0,UMLS:C0392680_shortness of breath

In [21]:
df.isnull().sum()

Disease                        0
Count of Disease Occurrence    0
Symptom                        1
dtype: int64

In [22]:
df[df['Symptom'].isnull()]

                         Disease  Count of Disease Occurrence Symptom
1622  UMLS:C0014118_endocarditis                         71.0     NaN

In [23]:
df = df.dropna(subset = ('Symptom'))

In [24]:
df.head(15)

,Disease,Count of Disease Occurrence,Symptom
0,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0008031_pain chest
1,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0392680_shortness of breath
2,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0012833_dizziness
3,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0004093_asthenia
4,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0085639_fall
5,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0039070_syncope
6,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0042571_vertigo
7,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0038990_sweat^UMLS:C0700590_sweating inc...
8,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0030252_palpitation
9,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0027497_nausea
10,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0002962_angina pectoris
11,UMLS:C0020538_hypertensive disease,3363.0,UMLS:C0438716_pressure chest
12,UMLS:C0011847_diabetes,1421.0,UMLS:C0032617_polyuria
13,UMLS:C0011847_diabetes,1421.0,UMLS:C0085602_polydypsia
14,UMLS:C0011847_diabetes,1421.0,UMLS:C0392680_shortness of breath

In [25]:
df.isnull().sum()

Disease                        0
Count of Disease Occurrence    0
Symptom                        0
dtype: int64

In [26]:
# Saving the cleaned dataset now

cleaned_data =  '/content/drive/MyDrive/AI_Healthcare_Diagnosis_system/cleaned_data.xlsx'

df.to_excel(cleaned_data, index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!